// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Gender is the predicate function for gender builders.
type Gender func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Rightoftreatment is the predicate function for rightoftreatment builders.
type Rightoftreatment func(*sql.Selector)

// Systemmember is the predicate function for systemmember builders.
type Systemmember func(*sql.Selector)
