// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHn holds the string denoting the hn field in the database.
	FieldHn = "hn"
	// FieldPatientName holds the string denoting the patientname field in the database.
	FieldPatientName = "patient_name"

	// EdgeGender holds the string denoting the gender edge name in mutations.
	EdgeGender = "gender"
	// EdgeRightoftreatment holds the string denoting the rightoftreatment edge name in mutations.
	EdgeRightoftreatment = "rightoftreatment"
	// EdgeSystemmember holds the string denoting the systemmember edge name in mutations.
	EdgeSystemmember = "systemmember"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// GenderTable is the table the holds the gender relation/edge.
	GenderTable = "patients"
	// GenderInverseTable is the table name for the Gender entity.
	// It exists in this package in order to avoid circular dependency with the "gender" package.
	GenderInverseTable = "genders"
	// GenderColumn is the table column denoting the gender relation/edge.
	GenderColumn = "Gender"
	// RightoftreatmentTable is the table the holds the rightoftreatment relation/edge.
	RightoftreatmentTable = "patients"
	// RightoftreatmentInverseTable is the table name for the Rightoftreatment entity.
	// It exists in this package in order to avoid circular dependency with the "rightoftreatment" package.
	RightoftreatmentInverseTable = "rightoftreatments"
	// RightoftreatmentColumn is the table column denoting the rightoftreatment relation/edge.
	RightoftreatmentColumn = "Rightoftreatment"
	// SystemmemberTable is the table the holds the systemmember relation/edge.
	SystemmemberTable = "patients"
	// SystemmemberInverseTable is the table name for the Systemmember entity.
	// It exists in this package in order to avoid circular dependency with the "systemmember" package.
	SystemmemberInverseTable = "systemmembers"
	// SystemmemberColumn is the table column denoting the systemmember relation/edge.
	SystemmemberColumn = "Systemmember"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldHn,
	FieldPatientName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Patient type.
var ForeignKeys = []string{
	"Gender",
	"Rightoftreatment",
	"Systemmember",
}
