// Code generated by entc, DO NOT EDIT.

package rightoftreatment

import (
	"github.com/benyabooncharoen/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// RightoftreatmentName applies equality check predicate on the "rightoftreatmentName" field. It's identical to RightoftreatmentNameEQ.
func RightoftreatmentName(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameEQ applies the EQ predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameEQ(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameNEQ applies the NEQ predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameNEQ(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameIn applies the In predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameIn(vs ...string) predicate.Rightoftreatment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRightoftreatmentName), v...))
	})
}

// RightoftreatmentNameNotIn applies the NotIn predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameNotIn(vs ...string) predicate.Rightoftreatment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRightoftreatmentName), v...))
	})
}

// RightoftreatmentNameGT applies the GT predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameGT(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameGTE applies the GTE predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameGTE(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameLT applies the LT predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameLT(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameLTE applies the LTE predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameLTE(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameContains applies the Contains predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameContains(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameHasPrefix applies the HasPrefix predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameHasPrefix(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameHasSuffix applies the HasSuffix predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameHasSuffix(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameEqualFold applies the EqualFold predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameEqualFold(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRightoftreatmentName), v))
	})
}

// RightoftreatmentNameContainsFold applies the ContainsFold predicate on the "rightoftreatmentName" field.
func RightoftreatmentNameContainsFold(v string) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRightoftreatmentName), v))
	})
}

// HasPatients applies the HasEdge predicate on the "patients" edge.
func HasPatients() predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientsWith applies the HasEdge predicate on the "patients" edge with a given conditions (other predicates).
func HasPatientsWith(preds ...predicate.Patient) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PatientsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PatientsTable, PatientsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Rightoftreatment) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Rightoftreatment) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Rightoftreatment) predicate.Rightoftreatment {
	return predicate.Rightoftreatment(func(s *sql.Selector) {
		p(s.Not())
	})
}
