// Code generated by entc, DO NOT EDIT.

package systemmember

const (
	// Label holds the string label denoting the systemmember type in the database.
	Label = "systemmember"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystemmemberName holds the string denoting the systemmembername field in the database.
	FieldSystemmemberName = "systemmember_name"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgePatients holds the string denoting the patients edge name in mutations.
	EdgePatients = "patients"

	// Table holds the table name of the systemmember in the database.
	Table = "systemmembers"
	// PatientsTable is the table the holds the patients relation/edge.
	PatientsTable = "patients"
	// PatientsInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientsInverseTable = "patients"
	// PatientsColumn is the table column denoting the patients relation/edge.
	PatientsColumn = "Systemmember"
)

// Columns holds all SQL columns for systemmember fields.
var Columns = []string{
	FieldID,
	FieldSystemmemberName,
	FieldPassword,
}

var (
	// SystemmemberNameValidator is a validator for the "systemmemberName" field. It is called by the builders before save.
	SystemmemberNameValidator func(string) error
	// PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
