// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/benyabooncharoen/app/ent/patient"
	"github.com/benyabooncharoen/app/ent/predicate"
	"github.com/benyabooncharoen/app/ent/rightoftreatment"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RightoftreatmentUpdate is the builder for updating Rightoftreatment entities.
type RightoftreatmentUpdate struct {
	config
	hooks      []Hook
	mutation   *RightoftreatmentMutation
	predicates []predicate.Rightoftreatment
}

// Where adds a new predicate for the builder.
func (ru *RightoftreatmentUpdate) Where(ps ...predicate.Rightoftreatment) *RightoftreatmentUpdate {
	ru.predicates = append(ru.predicates, ps...)
	return ru
}

// SetRightoftreatmentName sets the rightoftreatmentName field.
func (ru *RightoftreatmentUpdate) SetRightoftreatmentName(s string) *RightoftreatmentUpdate {
	ru.mutation.SetRightoftreatmentName(s)
	return ru
}

// AddPatientIDs adds the patients edge to Patient by ids.
func (ru *RightoftreatmentUpdate) AddPatientIDs(ids ...int) *RightoftreatmentUpdate {
	ru.mutation.AddPatientIDs(ids...)
	return ru
}

// AddPatients adds the patients edges to Patient.
func (ru *RightoftreatmentUpdate) AddPatients(p ...*Patient) *RightoftreatmentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.AddPatientIDs(ids...)
}

// Mutation returns the RightoftreatmentMutation object of the builder.
func (ru *RightoftreatmentUpdate) Mutation() *RightoftreatmentMutation {
	return ru.mutation
}

// RemovePatientIDs removes the patients edge to Patient by ids.
func (ru *RightoftreatmentUpdate) RemovePatientIDs(ids ...int) *RightoftreatmentUpdate {
	ru.mutation.RemovePatientIDs(ids...)
	return ru
}

// RemovePatients removes patients edges to Patient.
func (ru *RightoftreatmentUpdate) RemovePatients(p ...*Patient) *RightoftreatmentUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ru.RemovePatientIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (ru *RightoftreatmentUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RightoftreatmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RightoftreatmentUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RightoftreatmentUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RightoftreatmentUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RightoftreatmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rightoftreatment.Table,
			Columns: rightoftreatment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rightoftreatment.FieldID,
			},
		},
	}
	if ps := ru.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.RightoftreatmentName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: rightoftreatment.FieldRightoftreatmentName,
		})
	}
	if nodes := ru.mutation.RemovedPatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rightoftreatment.PatientsTable,
			Columns: []string{rightoftreatment.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rightoftreatment.PatientsTable,
			Columns: []string{rightoftreatment.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rightoftreatment.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RightoftreatmentUpdateOne is the builder for updating a single Rightoftreatment entity.
type RightoftreatmentUpdateOne struct {
	config
	hooks    []Hook
	mutation *RightoftreatmentMutation
}

// SetRightoftreatmentName sets the rightoftreatmentName field.
func (ruo *RightoftreatmentUpdateOne) SetRightoftreatmentName(s string) *RightoftreatmentUpdateOne {
	ruo.mutation.SetRightoftreatmentName(s)
	return ruo
}

// AddPatientIDs adds the patients edge to Patient by ids.
func (ruo *RightoftreatmentUpdateOne) AddPatientIDs(ids ...int) *RightoftreatmentUpdateOne {
	ruo.mutation.AddPatientIDs(ids...)
	return ruo
}

// AddPatients adds the patients edges to Patient.
func (ruo *RightoftreatmentUpdateOne) AddPatients(p ...*Patient) *RightoftreatmentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.AddPatientIDs(ids...)
}

// Mutation returns the RightoftreatmentMutation object of the builder.
func (ruo *RightoftreatmentUpdateOne) Mutation() *RightoftreatmentMutation {
	return ruo.mutation
}

// RemovePatientIDs removes the patients edge to Patient by ids.
func (ruo *RightoftreatmentUpdateOne) RemovePatientIDs(ids ...int) *RightoftreatmentUpdateOne {
	ruo.mutation.RemovePatientIDs(ids...)
	return ruo
}

// RemovePatients removes patients edges to Patient.
func (ruo *RightoftreatmentUpdateOne) RemovePatients(p ...*Patient) *RightoftreatmentUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ruo.RemovePatientIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (ruo *RightoftreatmentUpdateOne) Save(ctx context.Context) (*Rightoftreatment, error) {

	var (
		err  error
		node *Rightoftreatment
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RightoftreatmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RightoftreatmentUpdateOne) SaveX(ctx context.Context) *Rightoftreatment {
	r, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return r
}

// Exec executes the query on the entity.
func (ruo *RightoftreatmentUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RightoftreatmentUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RightoftreatmentUpdateOne) sqlSave(ctx context.Context) (r *Rightoftreatment, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   rightoftreatment.Table,
			Columns: rightoftreatment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: rightoftreatment.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Rightoftreatment.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := ruo.mutation.RightoftreatmentName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: rightoftreatment.FieldRightoftreatmentName,
		})
	}
	if nodes := ruo.mutation.RemovedPatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rightoftreatment.PatientsTable,
			Columns: []string{rightoftreatment.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.PatientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rightoftreatment.PatientsTable,
			Columns: []string{rightoftreatment.PatientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	r = &Rightoftreatment{config: ruo.config}
	_spec.Assign = r.assignValues
	_spec.ScanValues = r.scanValues()
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rightoftreatment.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return r, nil
}
