// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/benyabooncharoen/app/ent/rightoftreatment"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Rightoftreatment is the model entity for the Rightoftreatment schema.
type Rightoftreatment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RightoftreatmentName holds the value of the "rightoftreatmentName" field.
	RightoftreatmentName string `json:"rightoftreatmentName,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RightoftreatmentQuery when eager-loading is set.
	Edges RightoftreatmentEdges `json:"edges"`
}

// RightoftreatmentEdges holds the relations/edges for other nodes in the graph.
type RightoftreatmentEdges struct {
	// Patients holds the value of the patients edge.
	Patients []*Patient
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PatientsOrErr returns the Patients value or an error if the edge
// was not loaded in eager-loading.
func (e RightoftreatmentEdges) PatientsOrErr() ([]*Patient, error) {
	if e.loadedTypes[0] {
		return e.Patients, nil
	}
	return nil, &NotLoadedError{edge: "patients"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rightoftreatment) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // rightoftreatmentName
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rightoftreatment fields.
func (r *Rightoftreatment) assignValues(values ...interface{}) error {
	if m, n := len(values), len(rightoftreatment.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	r.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field rightoftreatmentName", values[0])
	} else if value.Valid {
		r.RightoftreatmentName = value.String
	}
	return nil
}

// QueryPatients queries the patients edge of the Rightoftreatment.
func (r *Rightoftreatment) QueryPatients() *PatientQuery {
	return (&RightoftreatmentClient{config: r.config}).QueryPatients(r)
}

// Update returns a builder for updating this Rightoftreatment.
// Note that, you need to call Rightoftreatment.Unwrap() before calling this method, if this Rightoftreatment
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Rightoftreatment) Update() *RightoftreatmentUpdateOne {
	return (&RightoftreatmentClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (r *Rightoftreatment) Unwrap() *Rightoftreatment {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rightoftreatment is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Rightoftreatment) String() string {
	var builder strings.Builder
	builder.WriteString("Rightoftreatment(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", rightoftreatmentName=")
	builder.WriteString(r.RightoftreatmentName)
	builder.WriteByte(')')
	return builder.String()
}

// Rightoftreatments is a parsable slice of Rightoftreatment.
type Rightoftreatments []*Rightoftreatment

func (r Rightoftreatments) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
