// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/benyabooncharoen/app/ent/schema"
	"github.com/benyabooncharoen/app/ent/systemmember"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	systemmemberFields := schema.Systemmember{}.Fields()
	_ = systemmemberFields
	// systemmemberDescSystemmemberName is the schema descriptor for systemmemberName field.
	systemmemberDescSystemmemberName := systemmemberFields[0].Descriptor()
	// systemmember.SystemmemberNameValidator is a validator for the "systemmemberName" field. It is called by the builders before save.
	systemmember.SystemmemberNameValidator = systemmemberDescSystemmemberName.Validators[0].(func(string) error)
	// systemmemberDescPassword is the schema descriptor for Password field.
	systemmemberDescPassword := systemmemberFields[1].Descriptor()
	// systemmember.PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	systemmember.PasswordValidator = systemmemberDescPassword.Validators[0].(func(string) error)
}
