/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntGender,
    EntGenderFromJSON,
    EntGenderFromJSONTyped,
    EntGenderToJSON,
    EntRightoftreatment,
    EntRightoftreatmentFromJSON,
    EntRightoftreatmentFromJSONTyped,
    EntRightoftreatmentToJSON,
    EntSystemmember,
    EntSystemmemberFromJSON,
    EntSystemmemberFromJSONTyped,
    EntSystemmemberToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * 
     * @type {EntGender}
     * @memberof EntPatientEdges
     */
    gender?: EntGender;
    /**
     * 
     * @type {EntRightoftreatment}
     * @memberof EntPatientEdges
     */
    rightoftreatment?: EntRightoftreatment;
    /**
     * 
     * @type {EntSystemmember}
     * @memberof EntPatientEdges
     */
    systemmember?: EntSystemmember;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gender': !exists(json, 'Gender') ? undefined : EntGenderFromJSON(json['Gender']),
        'rightoftreatment': !exists(json, 'Rightoftreatment') ? undefined : EntRightoftreatmentFromJSON(json['Rightoftreatment']),
        'systemmember': !exists(json, 'Systemmember') ? undefined : EntSystemmemberFromJSON(json['Systemmember']),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gender': EntGenderToJSON(value.gender),
        'rightoftreatment': EntRightoftreatmentToJSON(value.rightoftreatment),
        'systemmember': EntSystemmemberToJSON(value.systemmember),
    };
}


