/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatientEdges,
    EntPatientEdgesFromJSON,
    EntPatientEdgesFromJSONTyped,
    EntPatientEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatient
 */
export interface EntPatient {
    /**
     * 
     * @type {EntPatientEdges}
     * @memberof EntPatient
     */
    edges?: EntPatientEdges;
    /**
     * 
     * @type {number}
     * @memberof EntPatient
     */
    gender?: number;
    /**
     * Hn holds the value of the "hn" field.
     * @type {string}
     * @memberof EntPatient
     */
    hn?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPatient
     */
    id?: number;
    /**
     * PatientName holds the value of the "patientName" field.
     * @type {string}
     * @memberof EntPatient
     */
    patientName?: string;
    /**
     * 
     * @type {number}
     * @memberof EntPatient
     */
    rightoftreatment?: number;
    /**
     * 
     * @type {number}
     * @memberof EntPatient
     */
    systemmember?: number;
}

export function EntPatientFromJSON(json: any): EntPatient {
    return EntPatientFromJSONTyped(json, false);
}

export function EntPatientFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntPatientEdgesFromJSON(json['edges']),
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'hn': !exists(json, 'hn') ? undefined : json['hn'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'patientName': !exists(json, 'patientName') ? undefined : json['patientName'],
        'rightoftreatment': !exists(json, 'rightoftreatment') ? undefined : json['rightoftreatment'],
        'systemmember': !exists(json, 'systemmember') ? undefined : json['systemmember'],
    };
}

export function EntPatientToJSON(value?: EntPatient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntPatientEdgesToJSON(value.edges),
        'gender': value.gender,
        'hn': value.hn,
        'id': value.id,
        'patientName': value.patientName,
        'rightoftreatment': value.rightoftreatment,
        'systemmember': value.systemmember,
    };
}


