/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRightoftreatmentEdges,
    EntRightoftreatmentEdgesFromJSON,
    EntRightoftreatmentEdgesFromJSONTyped,
    EntRightoftreatmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRightoftreatment
 */
export interface EntRightoftreatment {
    /**
     * 
     * @type {EntRightoftreatmentEdges}
     * @memberof EntRightoftreatment
     */
    edges?: EntRightoftreatmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRightoftreatment
     */
    id?: number;
    /**
     * RightoftreatmentName holds the value of the "rightoftreatmentName" field.
     * @type {string}
     * @memberof EntRightoftreatment
     */
    rightoftreatmentName?: string;
}

export function EntRightoftreatmentFromJSON(json: any): EntRightoftreatment {
    return EntRightoftreatmentFromJSONTyped(json, false);
}

export function EntRightoftreatmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRightoftreatment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntRightoftreatmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rightoftreatmentName': !exists(json, 'rightoftreatmentName') ? undefined : json['rightoftreatmentName'],
    };
}

export function EntRightoftreatmentToJSON(value?: EntRightoftreatment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntRightoftreatmentEdgesToJSON(value.edges),
        'id': value.id,
        'rightoftreatmentName': value.rightoftreatmentName,
    };
}


