export * from './ControllersPatient';
export * from './EntGender';
export * from './EntGenderEdges';
export * from './EntPatient';
export * from './EntPatientEdges';
export * from './EntRightoftreatment';
export * from './EntRightoftreatmentEdges';
export * from './EntSystemmember';
export * from './EntSystemmemberEdges';
